### ISSUE TITLE
custom string ID can not impl Scanner

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1481]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

![image](https://user-images.githubusercontent.com/1777211/115344923-a05b0d00-a1e0-11eb-83f4-9dfc4bcb6404.png)
![image](https://user-images.githubusercontent.com/1777211/115344934-a51fc100-a1e0-11eb-9edf-d7b6f5bc0668.png)

```go
type ID string
func (u *ID) Scan(src interface{}) error {
	if src == nil {
		return fmt.Errorf("id: expected a value")
	}
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("id: expected a string")
	}
	*u = ID(s)
	return nil
}
```

## Expected Behavior 🤔

custom string ID works

## Steps to Reproduce 🕹

https://github.com/wenerme/ent-demo

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | master v0.8.1-0.20210419154037-b3041725d2c7   |
| Database    | -   |
| Driver      | - |

**Comment by wenerme** [comment]
Maybe should use `*so.DeletedByID = *value.S.(*models.ID)` ?

**Comment by a8m** [comment]
Hey @wenerme and thanks for reporting this. Can you please share here how the field was declared in the schema?

**Comment by wenerme** [comment]
@a8m Maybe this is caused by using `modules.ID` as go type, I'll try to use `new(modules.ID)` and check again.

**Comment by wenerme** [comment]
@a8m After using `new(modules.ID)` the problem seems solved, but the primary key has to be *modules.ID too, but the query sqlAll not happy with this

![image](https://user-images.githubusercontent.com/1777211/115348761-a30c3100-a1e5-11eb-8466-575bf4c1a1e6.png)

**Comment by wenerme** [comment]
@a8m Updated the reproduce demo, here is the problem https://github.com/wenerme/ent-demo/blob/master/ent/pet_query.go#L385

**Comment by wenerme** [comment]
Seems 0.8 is not easy to get, after upgrade, only the ptr impl the Scanner interface, make some field looks odd, e.g. the primary ID has to be ptr, a required id field has to be ptr, using struct as ID field makes the dx worse.

**Comment by a8m** [comment]
I think https://github.com/ent/ent/pull/1483 should fix the problem. Can you look at this PR and let me know if these test cases cover your use case? Thanks

**Comment by wenerme** [comment]
@a8m OK, I'll check this

**Comment by wenerme** [comment]
@a8m problem still exists

if using *models.ID as primary id, edge us *models.ID the problem is

![image](https://user-images.githubusercontent.com/1777211/115365232-c4294d80-a1f6-11eb-909f-7cb6efbfae6f.png)

if using models.ID as primary id, edge us *models.ID  the problem is

![image](https://user-images.githubusercontent.com/1777211/115365367-e58a3980-a1f6-11eb-816d-b417f5b19cab.png)

if all using models.ID the code is __OK__

but the runtime error

```
panic: failed scanning rows: sql: Scan error on column index 1, name "owner_id": id: expected a value [recovered]
	panic: failed scanning rows: sql: Scan error on column index 1, name "owner_id": id: expected a value
```

code here https://github.com/wenerme/ent-demo

**Comment by wenerme** [comment]
Seems the last runtime error is not related to this problem.

**Comment by wenerme** [comment]
The last error stack, related to the id type

```
database/sql.(*Rows).Scan at sql.go:3146
entgo.io/ent/dialect/sql/sqlgraph.(*updater).scan at graph.go:840
entgo.io/ent/dialect/sql/sqlgraph.(*updater).node at graph.go:690
entgo.io/ent/dialect/sql/sqlgraph.UpdateNode at graph.go:418
github.com/wenerme/ent-demo/ent.(*PetUpdateOne).sqlSave at pet_update.go:515
github.com/wenerme/ent-demo/ent.(*PetUpdateOne).Save.func1 at pet_update.go:373
entgo.io/ent.MutateFunc.Mutate at ent.go:347
github.com/wenerme/ent-demo/ent/schema.HookID.func1.1 at mixin_id.go:43
entgo.io/ent.MutateFunc.Mutate at ent.go:347
github.com/wenerme/ent-demo/ent.(*PetUpdateOne).Save at pet_update.go:380
github.com/wenerme/ent-demo/ent.(*PetUpdateOne).SaveX at pet_update.go:389
github.com/wenerme/ent-demo/test.TestClear at demo_test.go:27
testing.tRunner at testing.go:1194
runtime.goexit at asm_amd64.s:1371
 - Async stack trace
testing.(*T).Run at testing.go:1239
```

**Comment by a8m** [comment]
Hey @wenerme, I cloned your repository and updated ent to the latest version of master and it works for me. However, there's some change you need to do in your code and it's to not return an error on `nil` values in the `ID.Scan` method, because foreign keys are optional in your case (you call for `ClearOwningUserID` in your test case):


```diff
func (u *ID) Scan(src interface{}) error {
	if src == nil {
-		return fmt.Errorf("id: expected a value")
+		return nil
	}
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("id: expected a string")
	}
	*u = ID(s)
	return nil
}
```

Let me know if we can close the issue.

**Comment by wenerme** [comment]
My mistake, problem solved, the initial code is copy from https://github.com/ent/contrib/blob/8afe5dc42745447c22af1708b8ba197e520c2c3b/entgql/internal/todopulid/ent/schema/pulid/pulid.go#L63 , great work.
