### ISSUE TITLE
internal error: package "context" without types was imported from "entgo.io/ent"

### ISSUE THREAD

**Issue by mattn** [ent/ent#2155]
I don't figure out yet but latest package does not work on my environment.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
ent generate ent
```
output 
```
internal error: package "context" without types was imported from "entgo.io/ent"
```

## Expected Behavior 🤔

finish with successfully

## Steps to Reproduce 🕹

Steps:

1. just do `ent generate ent`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version devel go1.18-17980dff36 Wed Nov 10 05:08:25 2021 +0000 windows/amd64  |
| Ent         | latest commit  |
| Database    | SQLite3  |
| Driver      | https://github.com/mattn/go-sqlite3       |

**Comment by a8m** [comment]
Hey @mattn, why do you use `ent generate` and not `go generate ./ent`? You can read about the motivation for using `go generate` (and `go run`) here: https://entgo.io/docs/code-gen#version-compatibility-between-entc-and-ent

**Comment by mattn** [comment]
Ah, you are right. But same.

```
internal error: package "context" without types was imported from "entgo.io/ent"
exit status 1
ent\generate.go:3: running "go": exit status 1
```

**Comment by a8m** [comment]
Are you able to reproduce this? https://github.com/ent/bug

**Comment by mattn** [comment]
Ah, now I figure out what is wrong.

I used [entgen](https://github.com/mattn/entge) and it generate Uesrs from users table (not User). This is my problme. Sorry.

**Comment by mattn** [comment]
If you think this is problem in ent, I'll reopen this.

**Comment by a8m** [comment]
Thanks for the update.

**Comment by mattn** [comment]
Sorry, I could reproduce this on `bug` repository.

**Comment by mattn** [comment]
The error is generated in https://github.com/golang/tools/blob/c2c92fd21d5352e63b81483defea1fdb7425fefa/go/packages/packages.go#L938

**Comment by mattn** [comment]
This seems to be related on Go's version. I'm trying this on Go 1.18 (tip).

**Comment by mattn** [comment]
This is callstack.
```
panic: unreachable [recovered]
	panic: unreachable

goroutine 14 [running]:
go/types.(*Checker).handleBailout(0xc000194540, 0xc000177c78)
	C:/dev/go/src/go/types/check.go:279 +0x8b
panic({0x1368780, 0x14d1a18})
	C:/dev/go/src/runtime/panic.go:838 +0x207
golang.org/x/tools/go/packages.(*loader).loadPackage.func2({0xc000268031, 0x7})
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:937 +0x14d
golang.org/x/tools/go/packages.importerFunc.Import(0x0?, {0xc000268031?, 0xc000214de0?})
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:1003 +0x27
go/types.(*Checker).importPackage(0xc000194540, {0x14d1f20, 0xc000380080}, {0xc000268031, 0x7}, {0xc00006c7e0, 0x4b})
	C:/dev/go/src/go/types/resolver.go:162 +0x25c
go/types.(*Checker).collectObjects.func1({0x14d28a0?, 0xc00031c150?})
	C:/dev/go/src/go/types/resolver.go:262 +0x471
go/types.(*Checker).walkDecl(0xc00006c7e0?, {0x14d46a0?, 0xc000030240?}, 0xc000177b48)
	C:/dev/go/src/go/types/decl.go:467 +0x1c7
go/types.(*Checker).walkDecls(...)
	C:/dev/go/src/go/types/decl.go:454
go/types.(*Checker).collectObjects(0xc000194540)
	C:/dev/go/src/go/types/resolver.go:252 +0xc6d
go/types.(*Checker).checkFiles(0xc000194540, {0xc000350100?, 0xc000230500?, 0x3?})
	C:/dev/go/src/go/types/check.go:297 +0xb5
go/types.(*Checker).Files(...)
	C:/dev/go/src/go/types/check.go:284
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001ca2a0, 0xc00005d000)
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:961 +0x70c
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:799 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
	C:/dev/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	C:/dev/go/src/sync/once.go:59
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:787 +0x52
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:728 +0x2c
created by golang.org/x/tools/go/packages.(*loader).refine
	C:/Users/mattn/go/pkg/mod/golang.org/x/tools@v0.1.7/go/packages/packages.go:727 +0xb16
```

**Comment by preslavrachev** [comment]
@mattn I have just ended up with the exact same issue. I am also using a developer preview of Go 1.18, becausem yWeb framework exclusively works with generic type params. 

What is the resolution to get ent working with Go 1.18?

**Comment by preslavrachev** [comment]
I temporarily reverted to using Go 1.17, and I could indeed confirm that it works with it, but when using Go 1.18, it results in the aforementioned error.

**Comment by mattn** [comment]
Currently, I have no ideas to fix with Go 1.18.

**Comment by marwan-at-work** [comment]
This is also true with go1.18beta1

**Comment by a8m** [comment]
I think updating x/tools will solve the issue. Will give it a try tomorrow morning

**Comment by a8m** [comment]
Issue resolved on master. Please, see attached screenshot

![image](https://user-images.githubusercontent.com/7413593/146949246-51d201c7-4488-488d-98e0-652e366820dc.png)

Closing, but feel free to reopen if you still have issues.

**Comment by xmlking** [comment]
I also getting the same error 
```
GOWORK=off  go generate ./...                                                                                                                                                                          
2022/03/31 17:43:04 internal error: package "context" without types was imported from "entgo.io/ent"
--entgrpc_out: protoc-gen-entgrpc: Plugin failed with status code 1.
ent/proto/entpb/generate.go:2: running "protoc": exit status 1

```

**Comment by giautm** [comment]
Hello @xmlking, can you try the latest version of `entgo.io/contrib`? I think it fixed via https://github.com/ent/contrib/pull/276

```sh
go get -u entgo.io/contrib/entproto@master
go get entgo.io/contrib/entproto/cmd/protoc-gen-entgrpc@master
```

**Comment by xmlking** [comment]
it works. thanks 
```
go install entgo.io/contrib/entproto/cmd/protoc-gen-entgrpc@master 
```

**Comment by NeonWizard** [comment]
This issue is still occuring with go version `1.20`. Reverting to go version `1.19` fixes the issue.

**Comment by SparkLee** [comment]
> This issue is still occuring with go version `1.20`. Reverting to go version `1.19` fixes the issue.

same with me

**Comment by thuan1412** [comment]
> This issue is still occuring with go version 1.20. Reverting to go version 1.19 fixes the issue.


I got the same issue

**Comment by neilyoung** [comment]
Does show the same issue with GO 1.24.0 on MacOS and ent 0.14.1. No other way as to downgrade to 1.23.6

**Comment by SuzukiHonoka** [comment]
install latest ent fix this.

**Comment by neilyoung** [comment]
Confirmed

**Comment by kayprogrammer** [comment]
> I think updating x/tools will solve the issue. Will give it a try tomorrow morning

Had this issue and this your solution was the only thing that worked for me.
Thank you very much
