### ISSUE TITLE
Query pagination error: wrong number of arguments to function COUNT()

### ISSUE THREAD

**Issue by vincentluan** [ent/ent#2984]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
query := client.MyModel.Query()
r, err := query.Select(fields...).Paginate(...)
```
`err` is "wrong number of arguments to function COUNT()"

## Expected Behavior 🤔

Should return results normally as in version 0.10.0

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.1  |
| Ent         | 0.11.3   |
| Database    | SQLite3 |
| Driver      | github.com/mattn/go-sqlite3 v1.14.15 |

**Comment by giautm** [comment]
Hello @vincentluan, thank you for reporting the issue.

The query looks correct and should be working as normal. Can you provide the reproduce with https://github.com/ent/bug? It will help us find the root-cause faster, thanks!

**Comment by vincentluan** [comment]
Hello @giautm, I'm sorry to inform you that the issue is still there. I found in the console log this SQL statement:
```
SELECT COUNT(`my_models`.`id`, `my_models`.`created_at`, `my_models`.`updated_at`, `my_models`.`deleted_at`, `my_models`.`user_id`, `my_models`.`status`) FROM `my_models` WHERE `my_models`.`user_id` = ?
```
I tried the similar query at https://www.sqlitetutorial.net/tryit/query/sqlite-count-function/#7 and got the same error. It seems that SQLite3 COUNT() function doesn't support multiple fields selection. Do you think a fix could be release anytime soon?

**Comment by giautm** [comment]
Hello @vincentluan, what is the version of gqlgen? the issue come from the EntGQL package, so you have to upgrade it to the master branch.

**Comment by vincentluan** [comment]
@giautm There's no entgql in go.mod. But there is `entgo.io/contrib v0.3.2`, and I'm using ent from this repo master branch.

**Comment by vincentluan** [comment]
@giautm It's still having the same issue. The generated SQL query is still the same.

**Comment by giautm** [comment]
> @giautm It's still having the same issue. The generated SQL query is still the same.

Do you run the go generate again? Btw, please join our discord so we can talk faster

**Comment by vincentluan** [comment]
@giautm oh my bad. I forgot to run go generate. The issue is now gone, thank you. When do you think this fix is going to be released?

**Comment by giautm** [comment]
Hello @vincentluan, I'm so happy because the issue was gone.

The master branch is stable enough for use in the production environment (with the `go.mod` file as version locking). However, I will ask @a8m to create a new tag for the new users without having the same issue.

We welcome you to our community on Discord for faster support and response: https://discord.gg/qZmPgTE6RX

Again, thank you so much for reporting the issue and the effort for it.

**Comment by vincentluan** [comment]
Hello,

It's regretably that this issus is happening again with ent v0.11.7 and ent/contrb v0.3.5. Is there any way we can fix this quick?

**Comment by vincentluan** [comment]
Hello @giautm, are you still working on this project? Could you take a look at this issue any time soon?

**Comment by vincentluan** [comment]
For more information, the query selects some fields, but it shouldn't be passed to function COUNT() in sqlite

**Comment by a8m** [comment]
Hey @vincentluan, please update both `ent` and `contrib` packages to master and re-run codegen. This should solve the problem.

**Comment by vincentluan** [comment]
Hello @a8m, this is still happening and I have upgraded both `ent` and `contrib` to the latest commit on master.
And another error has presented itself: one of the `collectField` function in `gql_collection.go` is missing its declaration for `fieldSeen` and other variables.

**Comment by a8m** [comment]
Hey, @vincentluan! Can you open a PR in `ent/contrib` that reproduces this issue?

**Comment by giautm** [comment]
Hello @vincentluan, please send us an example to reproduce the issue. We will put it to the test to prevent this happen again. Sorry for your inconvenience.

**Comment by vincentluan** [comment]
Hey guys, it seems that the declaration of `fieldSeen` will be missing when using `Annotations(entgql.Skip())` in schema:
```
func (MyModel) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("table_1_id").
			Annotations(entgql.Skip()),
		field.Uint64("table_2_id").
			Annotations(entgql.Skip()),
	}
}
```

The error with function COUNT() is still happening with the latest version in master branches, using the same query as in my original example above.
```
# go.mod
entgo.io/contrib v0.4.6-0.20230514215512-b00990bedaf0
entgo.io/ent v0.12.4-0.20230523115418-d7b3a6c4f4dc
```

**Comment by giautm** [comment]
@vincentluan, noticed. It's intentional behavior now. We will discus about support this.

**Comment by giautm** [comment]
@vincentluan : please upgrade to latest commit on master branch. We pushed a fix here. :D

**Comment by vincentluan** [comment]
@giautm it's working now, thanks a lot for your help :D
